name: Net-IP-Resolver
version: 0.01
abstract: Resolve IPs to a particular network
author: Adam Kennedy <cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  File::Spec: 0.82
requires:
  perl: 5.005
  Net::IP::Match::XS: 0.03
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
