abstract: Resolve IPs to a particular network
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  File::Spec: 0.80
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
name: Net-IP-Resolver
no_index: 
  directory: 
    - inc
    - t
requires: 
  Net::IP::Match::XS: 0.03
version: 0.02
